DB_URIS:
    "users:Base": mysql+mysqlconnector://${DB_USER:root}:${DB_PASSWORD:}@${DB_SERVER:localhost}/${DB_NAME:users}

AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASS:guest}@${RABBIT_SERVER:localhost}:${RABBIT_PORT:5672}/${RABBIT_VHOST:}


LOGGING:
    version: 1
    disable_exsiting_loggers: False
    filters:
        truncate_request_trace:
            (): nameko_tracer.filters.TruncateCallArgsFilter
        truncate_response_trace:
            (): nameko_tracer.filters.TruncateResponseFilter
    formatters:
        default:
            format: "%(asctime)-15s [%(levelname)-4s] [users-service] [%(name)-12s] %(message)s"
        tracer:
            (): nameko_tracer.formatters.JSONFormatter
    handlers:
        default:
            level: INFO
            formatter: default
            class: logging.StreamHandler
        tracer:
            class: logging.StreamHandler
            formatter: tracer
    loggers:
        nameko_tracer:
            level: INFO
            handlers: [tracer]
            filters:
                - truncate_request_trace
                - truncate_response_trace
    root:
        level: INFO
        propagate: True
        handlers: [default]


MAIL_HOST: ${MAIL_HOST:}
EMAIL_USER: ${EMAIL_USER:}
EMAIL_PASSWORD: ${EMAIL_PASSWORD:}
EMAIL_SENDER: ${EMAIL_SENDER:}
