version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3-stretch
      - image: rabbitmq:3.7-management
      - image: circleci/mysql:5.6.36
        environment:
          MYSQL_DATABASE: demo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo pip install -U pip wheel setuptools
            sudo pip install -U -e ".[dev]"

      - run:
          name: Run tests
          command: |
            mkdir /tmp/coverage-hmtl
            ARGS=--disable-warnings HTMLCOV_DIR=/tmp/coverage-html make coverage

      - store_artifacts:
          path: /tmp/coverage-html
          destination: coverage-html
  
  build_images:
    docker:
      - image: circleci/python:3.7.3-stretch
    
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build docker images
          command: |
            make build docker-save
      
      - persist_to_workspace:
          root: docker-images
          paths:
            - users-services.tar

  push_images:
    docker:
      - image: circleci/python:3.7.3-stretch
    
    steps:
      - checkout
      - setup_remote_docker

      - attach_workspace:
        at: docker-images
      
      - run:
          name: Push docker images
          command: |
            make docker-login
            make docker-load
            make docker-tag
            make push-images


workflows:
  version: 2
  all-workflows:
    jobs:
      - test_approval:
          type: approval
      - test:
          requires:
            - test_approval
      - docker_approval:
          type: approval
      - build_images:
          requires:
            - docker_approval
      - push_images:
          requires:
            - build_images
          filters:
            branches:
              only: master
