version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7.3-stretch
      - image: rabbitmq:3.7-management
      - image: circleci/mysql:5.6.36
        environment:
          MYSQL_DATABASE: demo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo pip install -U pip wheel setuptools
            sudo pip install -U users-service/[dev]

      - run:
          name: Run tests
          command: |
            mkdir /tmp/coverage-hmtl
            ARGS=--disable-warnings HTMLCOV_DIR=/tmp/coverage-html make coverage

      - store_artifacts:
          path: /tmp/coverage-html
          destination: coverage-html


workflows:
  version: 2
  main-workflow:
    jobs:
      - test
